spring.application.name=SqlService

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Main datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/sqlservice
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Spring MVC
spring.mvc.pathmatch.use-suffix-pattern=false
spring.web.resources.add-mappings=false

# MinIO
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=sqlservice-tasks